version: "3"
services:
  test-es:
    image: opensearchproject/opensearch:2.12.0
    ports:
      - 9200:9200
      - 9600:9600
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch.yml:/tmp/elasticsearch.yml
      - ./setup-test.sh:/tmp/setup.sh
      - ./regionSynonyms.test.txt:/usr/share/opensearch/config/analysis/regionSynonyms.txt
      - ./wn_s_test.pl:/usr/share/opensearch/config/analysis/wn_s.pl
    environment:
      - NODE_NAME=es-data-0
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=sDf1sdfds@sdf!
      - cluster.name=opensearch-cluster
      - NODE_DATA=true
      - NODE_MASTER=true
      - NODE_INGEST=true
      - HTTP_ENABLE=true
      - DISCOVERY_SERVICE=localhost
      - NETWORK_HOST=0.0.0.0
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - plugins.security.disabled=true
