apiVersion: v1
kind: ConfigMap
metadata:
  name: "test-opa-policies"
data:
  my_custom_policy_files.json: {{ include "magda.filesToJson" (dict "root" . "filePattern" "policies/**/*" "removePrefix" "policies/" ) }} 