apiVersion: v1
kind: Service
metadata:
  name: "{{ template "magda.opensearch.mainService" . }}"
  labels:
    component: opensearch
    role: {{- if .Values.client.enabled -}} "client" {{- else if .Values.master.enabled -}} "master" {{- else -}} "data" {{- end }}
spec:
  selector:
    component: opensearch
    role: {{- if .Values.client.enabled -}} "client" {{- else if .Values.master.enabled -}} "master" {{- else -}} "data" {{- end }}
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
