apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensearch.data.fullname" . }}-headless
  labels:
    component: opensearch
    role: data
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    component: opensearch
    role: data
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
  - name: metrics
    port: 9600
