{{- if .Values.master.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "opensearch.master.fullname" . }}-headless"
  labels:
    component: opensearch
    role: master
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    component: opensearch
    role: master
  ports:
  - name: http
    port: {{ .Values.httpPort }}
    protocol: TCP
  - name: transport
    port: {{ .Values.transportPort }}
    protocol: TCP
  - name: metrics
    port: {{ .Values.metricsPort }}
{{- end }}