image: 
  name: "magda-storage-api"
  # repository: 
  # tag: 
  # pullPolicy: 
  # pullSecrets: 

defaultImage:
  repository: "ghcr.io/magda-io"
  pullPolicy: IfNotPresent
  pullSecrets: false

resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 50m

# -- Whether or not auto create `storage-secrets`.
# When auto created, random 20 chars will be generated for `accessKey` and random 40 chars will be generated for `secretKey`.
# When use minio as gateway mode, you might want to manualy generate the secret in order supply cloud provider secrets. e.g.
# <ul>
#   <li>awsAccessKeyId: aws s3 access key id if use AWS s3</li>
#   <li>awsSecretAccessKey: aws s3 secret access key id if use AWS s3</li>
#   <li>gcs_key.json: GCS key file if use google GCS</li>
# </ul>
autoCreateSecrets: true

# -- Create `defaultBuckets` on startup.
autoCreateBuckets: true

# -- Default buckets to create on startup.
# If no value is provided `global.defaultDatasetBucket` will be used.
defaultBuckets: []

# -- specify bucket region
# @default -- "unspecified-region"
minioRegion: ""

# -- Whether or not to connect to minio server with SSL connection
minioEnableSSL: false

# -- The port for storage api to listen on
listenPort: 6121

# -- The URL of the authorization API
authApiUrl: "http://authorization-api/v0"

# -- The URL of the registry API
registryApiUrl: "http://registry-api/v0"

# -- The tenant ID to use for the storage API
tenantId: 0

# -- the file upload size limit of the storage API
uploadLimit: "100mb"

# -- when set to true, API will not query policy engine for auth decision but assume it's always permitted. 
# It's for debugging only.
skipAuth: false

minio:
  host: "minio"
  port: 9000
  nameOverride: "magda-minio"
  fullnameOverride: "magda-minio"
  existingSecret: "storage-secrets"
  resources:
    requests:
      memory: 256Mi
  persistence:
    size: 10Gi
  DeploymentUpdate:
    type: Recreate

